// Win-chance model, fitted against 3060 self-play games (118168 positions,
// 35358 held out for testing). Generated by sim/calibrate.js on 2026-09-24;
// do not edit by hand. Full report in docs/measurements/calibration.json.
//
// Held out:  1/(1+exp(-v/7))  log loss 0.50247, Brier 0.16093, worst reliability gap 17.3 points
//            fitted           log loss 0.44697, Brier 0.14738, worst reliability gap 3.1 points
window.FawaneesCalibration = {
  measured: true,
  source: '3060 self-play games, 118168 positions, fitted per game phase',
  games: 3060,
  positions: 118168,
  logLossBefore: 0.50247,
  logLossAfter: 0.44697,
  worstGapAfter: 0.031,
  centres: [0.083333,0.25,0.416667,0.583333,0.75,0.916667],
  // [turquoise to move, gold to move]
  a: [[0.0205,0.06069,0.08537,0.10546,0.15175,0.21736],[0.02528,0.05146,0.07837,0.10447,0.14992,0.21063]],
  b: [[0.08146,-0.0992,-0.17291,-0.18635,-0.25109,-0.15116],[0.08295,-0.04423,-0.05425,-0.04554,0.00458,-0.0359]],
  // value: search value in points from gold's side; phase: lanterns placed / total supply
  prob: function (value, phase, goldToMove) {
    const s = goldToMove ? 1 : 0, c = this.centres;
    let k = 0;
    while (k < c.length - 1 && phase > c[k + 1]) k++;
    const k2 = Math.min(k + 1, c.length - 1);
    const span = c[k2] - c[k];
    const t = span > 0 ? Math.max(0, Math.min(1, (phase - c[k]) / span)) : 0;
    const a = this.a[s][k] + (this.a[s][k2] - this.a[s][k]) * t;
    const b = this.b[s][k] + (this.b[s][k2] - this.b[s][k]) * t;
    return 1 / (1 + Math.exp(-(a * value + b)));
  },
};
