// Opening and swap policy, derived from 16380 self-play games at equal strength:
// every opening cell, both branches of the swap rule, every one of the 90 possible replies.
// Generated by sim/makeOpeningPolicy.js on 2026-09-24; do not edit by hand.
// Full study in docs/measurements/opening.json, discussion in docs/BALANCE.md.
//
// Taking the opening lantern leaves exactly the position that answering it leaves, with the colours
// exchanged, so the two branches are complements: across all 91 cells they add to 100% to
// within 2.2 points. The responder therefore just picks the better seat, and the
// opener's best answer is the opening that sits closest to even: 49.6%.
window.FawaneesOpening = {
  measured: true,
  source: '16380 self-play games at depth 3, every opening cell and every reply',
  games: 16380,
  openerWinRate: 0.4963,
  openerWinRateHalfWidth: 0.0499,
  // Openings within two points of the best, which is finer than the study can resolve.
  open: ["-1,-1","-1,-2","-1,2","-1,3","-2,-1","-2,-2","-2,0","-2,1","-2,2","-2,3","-2,4","-3,0","-3,1","-3,2","-3,3","-4,2","0,-2","0,-3","0,2","0,3","1,-2","1,-3","1,1","1,2","2,-1","2,-2","2,-3","2,-4","2,0","2,1","2,2","3,-1","3,-2","3,-3","3,0","4,-2"],
  // Opening cells where the second player does better by taking the lantern than by answering it.
  swapCells: ["-1,-1","-1,-2","-1,-3","-1,-4","-1,0","-1,1","-1,2","-1,3","-1,4","-1,5","-2,-1","-2,-2","-2,-3","-2,0","-2,1","-2,2","-2,3","-2,4","-2,5","-3,-1","-3,-2","-3,1","-3,2","-3,4","-3,5","-4,-1","-4,0","-4,1","-4,2","-4,3","-4,4","-4,5","-5,0","-5,1","-5,2","-5,3","-5,4","-5,5","0,-1","0,-2","0,-4","0,-5","0,1","0,2","0,4","0,5","1,-1","1,-2","1,-3","1,-4","1,-5","1,0","1,1","1,2","1,3","1,4","2,-1","2,-2","2,-3","2,-4","2,-5","2,0","2,1","2,2","2,3","3,-1","3,-2","3,-4","3,-5","3,1","3,2","4,-1","4,-2","4,-3","4,-4","4,-5","4,0","4,1","5,-1","5,-2","5,-3","5,-4","5,-5","5,0"],
  pickOpening: function (geo) {
    const pool = this.open.map(k => geo.index.get(k)).filter(i => i !== undefined);
    return pool[Math.floor(Math.random() * pool.length)];
  },
  shouldSwap: function (cell, geo) {
    const c = geo.cells[cell];
    return this.swapCells.indexOf(c.q + ',' + c.r) >= 0;
  },
};
