// Puzzles the machine found in its own games. Generated by sim/minePuzzles.js; not yet mined.
window.FawaneesPuzzles = { measured: false, radius: 5, games: 0, positionsScanned: 0, candidates: 0, verifyDepth: 6, list: [] };
