// Puzzles the machine found in its own games. Generated by sim/minePuzzles.js on 2026-09-24;
// do not edit by hand. Full report in docs/measurements/puzzles.json.
//
// 700 self-play games, 25934 positions examined, 40 candidates,
// 40 distinct after symmetry, 31 survived a depth-5 recheck, 16 kept.
// "difficulty" is the shallowest search depth that finds the answer: 2 means a machine looking two
// moves ahead sees it, 4 means it needs to look 4.
window.FawaneesPuzzles = {
  measured: true,
  radius: 5,
  games: 700,
  positionsScanned: 25934,
  candidates: 40,
  verifyDepth: 5,
  list: [
    { board: '0000000002000001000000011200000010120000000012000100000200000001010000000000010000000000000', side: 2, hands: [0, 16, 17], answer: '-1,-1', flips: 3, margin: 17, difficulty: 2, swing: 13, waves: [["-1,0","0,-1"],["-2,0"]] },
    { board: '1000000010000001011100020010000022101010002001201000002020100000000100002202100000200000000', side: 1, hands: [0, 11, 11], answer: '2,0', flips: 3, margin: 13, difficulty: 2, swing: 15, waves: [["0,1","3,0"],["1,0"]] },
    { board: '0000010220100002101110200000012021111220022200122000200100222000202000022202020000000000000', side: 2, hands: [0, 5, 6], answer: '0,-1', flips: 3, margin: 13, difficulty: 2, swing: 15, waves: [["-1,-1"],["-3,1","-1,0"]] },
    { board: '0200000001112002011000222100000020200120122021111002000010110020010000202000100001100000100', side: 1, hands: [0, 6, 6], answer: '-1,-1', flips: 3, margin: 12, difficulty: 2, swing: 11, waves: [["-1,0","0,-1"],["-2,0"]] },
    { board: '0020000200200001100201011111010222201000002220110000202220020000000200020202200110100001000', side: 2, hands: [0, 5, 6], answer: '-2,-2', flips: 3, margin: 12, difficulty: 2, swing: 11, waves: [["-2,-1"],["-3,0"],["-2,0"]] },
    { board: '0000020010100102000100002100100002211000000222110100000220000202022010002202000000000000000', side: 2, hands: [0, 9, 10], answer: '-3,1', flips: 3, margin: 11, difficulty: 2, swing: 13, waves: [["-2,1"],["-1,1"],["0,1"]] },
    { board: '0000000220200101202000011202000011020000000100202000000202200001220000002202000200100001000', side: 2, hands: [0, 9, 10], answer: '-3,-1', flips: 4, margin: 16, difficulty: 2, swing: 17, waves: [["-3,0"],["-2,0"],["-2,-1"],["-1,-1"]] },
    { board: '0011000001010101111100001000012010001010011100011020100001012001000002011010120010021002200', side: 1, hands: [0, 5, 5], answer: '2,2', flips: 5, margin: 8, difficulty: 2, swing: 11, waves: [["-1,-4","3,2"],["2,3"],["1,4"],["0,5"]] },
    { board: '0101002020110002201000220001001002200001012220000021000111101011001100110110001110002110100', side: 1, hands: [0, 3, 3], answer: '-1,-2', flips: 3, margin: 10, difficulty: 3, swing: 12, waves: [["0,-3"],["0,-2"],["0,-1"]] },
    { board: '0010000200020202202020022000200101120200101111000000001110020011010100001111000110000000020', side: 1, hands: [0, 6, 6], answer: '-3,-1', flips: 3, margin: 10, difficulty: 3, swing: 13, waves: [["-2,-1"],["-2,0"],["-3,0"]] },
    { board: '0010200010200011122020000022000000202200021000022100011020120001022000001102200000202000100', side: 2, hands: [0, 6, 7], answer: '-5,1', flips: 3, margin: 9, difficulty: 3, swing: 14, waves: [["-5,2","1,2"],["-4,1"]] },
    { board: '0000000010100001010020110111000211011000202010100100220000101202011000221110110110100000011', side: 1, hands: [0, 4, 4], answer: '2,-4', flips: 3, margin: 8, difficulty: 3, swing: 10, waves: [["2,-3","3,-4"],["1,-3"]] },
    { board: '0010110000000021111111011100010211000000002200011110020200110000200002202001001101100110110', side: 2, hands: [0, 3, 4], answer: '-2,-2', flips: 3, margin: 8, difficulty: 3, swing: 12, waves: [["-1,-2"],["-1,-1"],["-2,-1"]] },
    { board: '0000000200000011101120000010000010110220001111202010020002000002222200000010100020000000000', side: 1, hands: [0, 9, 9], answer: '3,-2', flips: 4, margin: 28, difficulty: 3, swing: 24, waves: [["2,-2"],["2,-1"],["0,1","2,0"]] },
    { board: '2110002200000122111000100100001022000000002200000000020200200000000100000001010000100100000', side: 1, hands: [0, 11, 11], answer: '-2,-1', flips: 5, margin: 12, difficulty: 3, swing: 14, waves: [["-3,0"],["-3,-1"],["-4,0"],["-4,-1"],["-5,0"]] },
    { board: '0200100000000221111102020100000222001120022220110020022200222002000120100001000100001000000', side: 2, hands: [0, 5, 5], answer: '-1,1', flips: 3, margin: 6, difficulty: 4, swing: 17, waves: [["-2,1"],["-3,1"],["-3,0"]] },
  ],
};
